import { Drug, PharmacyStore, DrugOffer, Order, DisputeCase, SystemMetric, MicroserviceHealth, FlaggedFeedAlert } from './types';

export const mockStores: PharmacyStore[] = [
  {
    id: 'store-1',
    name: 'ExpressRx Central Hub',
    code: 'STR-80211',
    address: '840 Market Street, Suite 100',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    rating: 4.9,
    reviewCount: 3420,
    distanceMiles: 1.4,
    isVerifiedHub: true,
    hasDriveThru: true,
    hasCurbside: true,
    fulfillmentTime: 'Under 2 hours',
    slaScore: 99.8,
    phone: '(555) 234-8900',
    isChain: false,
  },
  {
    id: 'store-2',
    name: 'MedPlus Express Pharmacy',
    code: 'STR-80214',
    address: '1420 S 6th Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62703',
    rating: 4.8,
    reviewCount: 1850,
    distanceMiles: 2.8,
    isVerifiedHub: true,
    hasDriveThru: true,
    hasCurbside: false,
    fulfillmentTime: 'Same Day by 5 PM',
    slaScore: 98.4,
    phone: '(555) 345-9012',
    isChain: false,
  },
  {
    id: 'store-3',
    name: 'CostLess Apothecary & Compounding',
    code: 'STR-80218',
    address: '2210 Wabash Avenue',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    rating: 4.7,
    reviewCount: 940,
    distanceMiles: 3.6,
    isVerifiedHub: true,
    hasDriveThru: false,
    hasCurbside: true,
    fulfillmentTime: 'Next Day Morning',
    slaScore: 97.9,
    phone: '(555) 456-0123',
    isChain: false,
  },
  {
    id: 'store-4',
    name: 'Walgreens Net Fulfillment Partner',
    code: 'STR-80203',
    address: '325 W Jefferson St',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    rating: 4.6,
    reviewCount: 6100,
    distanceMiles: 0.9,
    isVerifiedHub: true,
    hasDriveThru: true,
    hasCurbside: true,
    fulfillmentTime: 'Same Day within 3 hrs',
    slaScore: 99.1,
    phone: '(555) 567-1234',
    isChain: true,
    chainName: 'Walgreens',
  },
  {
    id: 'store-5',
    name: 'CVS Health Direct Partner',
    code: 'STR-80208',
    address: '601 N Grand Ave W',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    rating: 4.5,
    reviewCount: 5200,
    distanceMiles: 1.1,
    isVerifiedHub: true,
    hasDriveThru: true,
    hasCurbside: false,
    fulfillmentTime: 'Same Day within 4 hrs',
    slaScore: 98.7,
    phone: '(555) 678-2345',
    isChain: true,
    chainName: 'CVS Pharmacy',
  },
  {
    id: 'store-6',
    name: 'Apex Care Pharmacy',
    code: 'STR-80225',
    address: '3100 S MacArthur Blvd',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    rating: 4.6,
    reviewCount: 420,
    distanceMiles: 4.2,
    isVerifiedHub: false,
    hasDriveThru: false,
    hasCurbside: false,
    fulfillmentTime: 'Next Day',
    slaScore: 96.5,
    phone: '(555) 789-3456',
    isChain: false,
  },
];

export const mockDrugs: Drug[] = [
  {
    id: 'metformin-500-er',
    name: 'Metformin HCl 500mg ER',
    genericName: 'Metformin Hydrochloride',
    strength: '500mg',
    form: 'Extended Release Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 60,
    brandEquivalent: 'Glucophage® XR',
    molecularFormula: 'C4H11N5 • HCl',
    clinicalSalt: 'Metformin Hydrochloride',
    therapeuticClass: 'Biguanide Antihyperglycemic',
    category: 'Diabetes',
    rxNormCode: '861004',
    ndcCode: '68180-337-01',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 076595 (FDA AB-Rated Equivalency)',
    lowestPrice: 4.12,
    medianPrice: 9.50,
    maxRetailPrice: 18.90,
    availableSellersCount: 18,
    prescriptionRequired: true,
    description: 'First-line medication for the treatment of type 2 diabetes, particularly in people who are overweight. Helps decrease hepatic glucose production and increase insulin sensitivity.',
    clinicalEquivalencyNote: 'Demonstrated bio-equivalent to Glucophage® XR. Active pharmaceutical ingredient (API) is structurally and therapeutically identical with FDA TE rating AB1, ensuring matching peak plasma concentration and AUC bioavailability.',
  },
  {
    id: 'atorvastatin-20',
    name: 'Atorvastatin Calcium 20mg',
    genericName: 'Atorvastatin Calcium',
    strength: '20mg',
    form: 'Film-Coated Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 30,
    brandEquivalent: 'Lipitor®',
    molecularFormula: 'C33H35FN2O5',
    clinicalSalt: 'Atorvastatin Calcium Trihydrate',
    therapeuticClass: 'HMG-CoA Reductase Inhibitor (Statin)',
    category: 'Cardiac Care',
    rxNormCode: '617314',
    ndcCode: '00093-7158-98',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 090548 (FDA AB-Rated)',
    lowestPrice: 8.40,
    medianPrice: 14.20,
    maxRetailPrice: 32.50,
    availableSellersCount: 22,
    prescriptionRequired: true,
    description: 'Used to lower low-density lipoprotein (LDL) cholesterol, raise high-density lipoprotein (HDL) cholesterol, and lower triglycerides in the blood to reduce risk of heart attack and stroke.',
    clinicalEquivalencyNote: 'Bioequivalent to Lipitor® 20mg. Manufactured in FDA cGMP-certified facilities with exact chemical purity and pharmacokinetic equivalence.',
  },
  {
    id: 'lisinopril-10',
    name: 'Lisinopril 10mg',
    genericName: 'Lisinopril',
    strength: '10mg',
    form: 'Oral Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 30,
    brandEquivalent: 'Zestril® / Prinivil®',
    molecularFormula: 'C21H31N3O5 • 2H2O',
    clinicalSalt: 'Lisinopril Dihydrate',
    therapeuticClass: 'ACE Inhibitor',
    category: 'Cardiac Care',
    rxNormCode: '314076',
    ndcCode: '68180-514-01',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 075899',
    lowestPrice: 3.25,
    medianPrice: 7.10,
    maxRetailPrice: 14.80,
    availableSellersCount: 14,
    prescriptionRequired: true,
    description: 'Angiotensin-converting enzyme (ACE) inhibitor prescribed for hypertension, congestive heart failure, and post-myocardial infarction recovery.',
    clinicalEquivalencyNote: 'Identical systemic receptor binding and therapeutic effect compared to reference listed drug Zestril®.',
  },
  {
    id: 'empagliflozin-10',
    name: 'Empagliflozin 10mg',
    genericName: 'Empagliflozin',
    strength: '10mg',
    form: 'Film-Coated Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 30,
    brandEquivalent: 'Jardiance®',
    molecularFormula: 'C23H27ClO7',
    clinicalSalt: 'Empagliflozin',
    therapeuticClass: 'SGLT2 Inhibitor',
    category: 'Diabetes',
    rxNormCode: '1545653',
    ndcCode: '00597-0152-30',
    fdaTeCode: 'AB2',
    fdaApprovalDate: 'ANDA 208442',
    lowestPrice: 24.50,
    medianPrice: 45.00,
    maxRetailPrice: 88.00,
    availableSellersCount: 9,
    prescriptionRequired: true,
    description: 'Inhibits sodium-glucose co-transporter 2 (SGLT2) in kidneys to lower blood sugar and reduce cardiovascular death risk in adults with type 2 diabetes.',
    clinicalEquivalencyNote: 'Therapeutically bioequivalent with matching renal clearance profile.',
  },
  {
    id: 'levothyroxine-50',
    name: 'Levothyroxine Sodium 50mcg',
    genericName: 'Levothyroxine Sodium',
    strength: '50mcg (0.05mg)',
    form: 'Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 30,
    brandEquivalent: 'Synthroid®',
    molecularFormula: 'C15H10I4NNaO4',
    clinicalSalt: 'Levothyroxine Sodium Hydrate',
    therapeuticClass: 'Thyroid Hormone Replacement',
    category: 'Thyroid',
    rxNormCode: '966224',
    ndcCode: '00074-6592-11',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 076187',
    lowestPrice: 6.10,
    medianPrice: 11.80,
    maxRetailPrice: 22.40,
    availableSellersCount: 16,
    prescriptionRequired: true,
    description: 'Replaces thyroxine (T4) normally produced by thyroid gland; treats hypothyroidism and prevents thyroid enlargement.',
    clinicalEquivalencyNote: 'Narrow therapeutic index compliant. Exact dissolution and potency specifications verified against reference standard.',
  },
  {
    id: 'amoxicillin-500',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    strength: '500mg',
    form: 'Capsule',
    dosageUnit: 'capsules',
    standardQuantity: 20,
    brandEquivalent: 'Amoxil®',
    molecularFormula: 'C16H19N3O5S • 3H2O',
    clinicalSalt: 'Amoxicillin Trihydrate',
    therapeuticClass: 'Aminopenicillin Antibacterial',
    category: 'Antibiotics',
    rxNormCode: '310965',
    ndcCode: '00093-2264-01',
    fdaTeCode: 'AA',
    fdaApprovalDate: 'ANDA 062882',
    lowestPrice: 5.90,
    medianPrice: 10.40,
    maxRetailPrice: 19.20,
    availableSellersCount: 12,
    prescriptionRequired: true,
    description: 'Broad-spectrum antibiotic used to treat bacterial infections including ear, nose, throat, skin, and lower respiratory tract infections.',
    clinicalEquivalencyNote: 'AA rating designates in-vivo bioequivalence problems are absent or resolved. Instant bio-potency equivalence.',
  },
  {
    id: 'sertraline-50',
    name: 'Sertraline HCl 50mg',
    genericName: 'Sertraline Hydrochloride',
    strength: '50mg',
    form: 'Film-Coated Tablet',
    dosageUnit: 'tablets',
    standardQuantity: 30,
    brandEquivalent: 'Zoloft®',
    molecularFormula: 'C17H17Cl2N • HCl',
    clinicalSalt: 'Sertraline Hydrochloride',
    therapeuticClass: 'SSRI Antidepressant',
    category: 'Mental Health',
    rxNormCode: '312940',
    ndcCode: '00049-4960-66',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 076881',
    lowestPrice: 7.15,
    medianPrice: 13.50,
    maxRetailPrice: 28.00,
    availableSellersCount: 15,
    prescriptionRequired: true,
    description: 'Selective serotonin reuptake inhibitor (SSRI) indicated for major depressive disorder, obsessive-compulsive disorder, and panic disorder.',
    clinicalEquivalencyNote: 'Bioequivalent to Zoloft® 50mg with identical serotonin transporter inhibition dynamics.',
  },
  {
    id: 'gabapentin-300',
    name: 'Gabapentin 300mg',
    genericName: 'Gabapentin',
    strength: '300mg',
    form: 'Capsule',
    dosageUnit: 'capsules',
    standardQuantity: 60,
    brandEquivalent: 'Neurontin®',
    molecularFormula: 'C9H17NO2',
    clinicalSalt: 'Gabapentin',
    therapeuticClass: 'GABA Analog / Neuropathic Pain',
    category: 'Pain Relief',
    rxNormCode: '310430',
    ndcCode: '00093-2144-01',
    fdaTeCode: 'AB1',
    fdaApprovalDate: 'ANDA 075350',
    lowestPrice: 6.80,
    medianPrice: 12.00,
    maxRetailPrice: 25.50,
    availableSellersCount: 17,
    prescriptionRequired: true,
    description: 'Prescribed for neuropathic pain and postherpetic neuralgia following shingles, as well as adjunctive therapy in partial seizures.',
    clinicalEquivalencyNote: 'Proven equivalent bioavailability and cellular absorption rate.',
  }
];

export const mockMetforminOffers: DrugOffer[] = [
  {
    id: 'offer-met-1',
    drugId: 'metformin-500-er',
    storeId: 'store-1',
    store: mockStores[0],
    price: 4.12,
    retailPrice: 18.90,
    stockCount: 540,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'same_day',
    deliveryFee: 0,
    isLowestPrice: true,
    isBestMatch: true,
    updatedSecondsAgo: 4,
  },
  {
    id: 'offer-met-2',
    drugId: 'metformin-500-er',
    storeId: 'store-2',
    store: mockStores[1],
    price: 5.80,
    retailPrice: 18.90,
    stockCount: 210,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'same_day',
    deliveryFee: 1.99,
    updatedSecondsAgo: 18,
  },
  {
    id: 'offer-met-3',
    drugId: 'metformin-500-er',
    storeId: 'store-3',
    store: mockStores[2],
    price: 6.45,
    retailPrice: 18.90,
    stockCount: 120,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'next_day',
    deliveryFee: 0,
    updatedSecondsAgo: 42,
  },
  {
    id: 'offer-met-4',
    drugId: 'metformin-500-er',
    storeId: 'store-4',
    store: mockStores[3],
    price: 9.20,
    retailPrice: 18.90,
    stockCount: 1200,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'same_day',
    deliveryFee: 2.99,
    updatedSecondsAgo: 11,
  },
  {
    id: 'offer-met-5',
    drugId: 'metformin-500-er',
    storeId: 'store-5',
    store: mockStores[4],
    price: 11.50,
    retailPrice: 18.90,
    stockCount: 900,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'same_day',
    deliveryFee: 2.99,
    updatedSecondsAgo: 5,
  },
  {
    id: 'offer-met-6',
    drugId: 'metformin-500-er',
    storeId: 'store-6',
    store: mockStores[5],
    price: 12.80,
    retailPrice: 18.90,
    stockCount: 45,
    inStock: true,
    packaging: '60 Tablets (1 Month Supply)',
    deliveryOption: 'next_day',
    deliveryFee: 3.50,
    updatedSecondsAgo: 95,
  },
];

export const getOffersForDrug = (drug: Drug): DrugOffer[] => {
  if (drug.id === 'metformin-500-er') {
    return mockMetforminOffers;
  }

  const packagingDesc = `${drug.standardQuantity} ${drug.dosageUnit.charAt(0).toUpperCase() + drug.dosageUnit.slice(1)} (1 Month Supply)`;
  const multipliers = [1.0, 1.38, 1.55, 2.15, 2.65, 3.05];
  const stockCounts = [310, 180, 95, 840, 620, 35];
  const deliveryOptions: ('same_day' | 'next_day' | 'pickup_only')[] = [
    'same_day',
    'same_day',
    'next_day',
    'same_day',
    'same_day',
    'next_day',
  ];
  const deliveryFees = [0, 1.99, 0, 2.99, 2.99, 3.50];

  return mockStores.map((store, idx) => {
    const rawPrice = drug.lowestPrice * (multipliers[idx] || 1.0);
    const price = Math.round(rawPrice * 100) / 100;
    const isLowest = idx === 0;

    return {
      id: `offer-${drug.id}-${store.id}`,
      drugId: drug.id,
      storeId: store.id,
      store,
      price,
      retailPrice: drug.maxRetailPrice,
      stockCount: stockCounts[idx] || 100,
      inStock: true,
      packaging: packagingDesc,
      deliveryOption: deliveryOptions[idx] || 'same_day',
      deliveryFee: deliveryFees[idx] || 0,
      isLowestPrice: isLowest,
      isBestMatch: isLowest,
      updatedSecondsAgo: (idx + 1) * 7,
    };
  });
};

export const mockInitialOrder: Order = {
  id: 'ord-89210',
  orderNumber: 'GM-89210',
  date: 'Today',
  time: '1:15 PM',
  status: 'out_for_delivery',
  patientName: 'Marcus Vance',
  patientPhone: '(555) 892-3401',
  deliveryAddress: '742 Evergreen Terrace, Springfield, IL 62704',
  store: mockStores[0],
  items: [
    {
      drugName: 'Metformin HCl 500mg ER',
      strength: '500mg',
      quantity: 60,
      unitPrice: 4.12,
      totalPrice: 4.12,
      prescriptionNumber: 'RX-99201',
      doctorName: 'Dr. Sarah Smith, MD',
    },
    {
      drugName: 'Atorvastatin Calcium 20mg',
      strength: '20mg',
      quantity: 30,
      unitPrice: 8.40,
      totalPrice: 8.40,
      prescriptionNumber: 'RX-99204',
      doctorName: 'Dr. Robert Taylor, MD',
    },
  ],
  subtotal: 12.52,
  retailValue: 51.40,
  savings: 38.88,
  dispensingFee: 1.20,
  deliveryFee: 0.00,
  total: 13.72,
  paymentMethod: 'Apple Pay (•••• 4242)',
  rfidSealNumber: 'SEAL-8910-A',
  isTamperProofVerified: true,
  courierName: 'Leo Gonzalez',
  courierVehicle: 'Silver Toyota Prius (Plate: 7XYZ89)',
  courierRating: 4.96,
  courierDeliveriesCount: 1420,
  estimatedArrival: '2:45 PM (In ~16 mins)',
  trackingStep: 4,
};

export const mockDisputeDossier: DisputeCase = {
  id: 'dsp-8910',
  caseNumber: 'DSP-8910',
  orderId: 'ord-89210',
  orderNumber: 'GM-89210',
  status: 'pending_review',
  severity: 'P0_CRITICAL',
  patientName: 'Marcus Vance',
  patientPhone: '(555) 892-3401',
  patientTrustScore: 5.0,
  patientPastOrders: 14,
  storeName: 'ExpressRx Central Hub (#STR-80211)',
  storeId: 'store-1',
  courierName: 'Leo Gonzalez (#DRV-4421)',
  courierId: 'drv-4421',
  category: 'Tamper Seal Violation',
  openedAt: '2:52 PM (12 mins ago)',
  disputedAmount: 13.72,
  description: 'Received prescription parcel with broken external security seal tape. The perforated safety seal clearly exposes the printed VOID pattern along the tear line. Bottle caps are sealed, but outer tamper-evident security tote was compromised prior to physical handoff.',
  forensicPhotoUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
  rfidDispatchedTime: '1:35:12 PM',
  courierHandoverTime: '1:42:04 PM',
  customerReceivedTime: '2:45:30 PM',
  weightAtStoreGrams: 340,
  weightAtCustomerGrams: 310,
};

export const mockSystemMetrics: SystemMetric[] = [
  {
    title: 'Gross Marketplace GMV',
    value: '$842,910',
    change: '+14.2% MoM',
    isPositive: true,
    subtext: '$28,450 24h run rate',
    icon: 'payments',
  },
  {
    title: 'Platform Take Commission',
    value: '$67,432',
    change: '+16.8%',
    isPositive: true,
    subtext: '8.0% effective blended rate',
    icon: 'account_balance',
  },
  {
    title: 'Active Orders Today',
    value: '18,420',
    change: '99.2% Fill SLA',
    isPositive: true,
    subtext: '142 orders/hr peak throughput',
    icon: 'inventory_2',
  },
  {
    title: 'Avg Patient Savings / Rx',
    value: '$28.40',
    change: '73.4% lower',
    isPositive: true,
    subtext: 'Compared to Big-Chain Retail MSRP',
    icon: 'savings',
  },
  {
    title: 'Connected Pharmacy Hubs',
    value: '428 Hubs',
    change: '+12 this week',
    isPositive: true,
    subtext: '99.98% inventory feed uptime',
    icon: 'storefront',
  },
];

export const mockMicroservices: MicroserviceHealth[] = [
  {
    name: 'Kong API Gateway',
    service: 'Edge Ingress & Auth Layer',
    uptime: '99.99%',
    latencyMs: 12,
    status: 'nominal',
    metric: '4,820 req/sec',
  },
  {
    name: 'Elastic Search',
    service: 'Canonical Medication Index',
    uptime: '100%',
    latencyMs: 4,
    status: 'nominal',
    metric: '12,480 items indexed',
  },
  {
    name: 'PostgreSQL Multi-Tenant',
    service: 'Order & Audit Ledger',
    uptime: '99.98%',
    latencyMs: 18,
    status: 'nominal',
    metric: '18 connection pools active',
  },
  {
    name: 'Redis Cluster',
    service: 'Real-Time Price Engine Cache',
    uptime: '99.99%',
    latencyMs: 1.2,
    status: 'nominal',
    metric: '98.4% cache hit rate',
  },
  {
    name: 'Webhook Dispatcher',
    service: 'Store POS Event Stream',
    uptime: '99.94%',
    latencyMs: 45,
    status: 'nominal',
    metric: '428 active listener nodes',
  },
  {
    name: 'Stripe & Escrow Vault',
    service: 'Payment & Fraud Gate',
    uptime: '100%',
    latencyMs: 140,
    status: 'nominal',
    metric: '0 pending chargebacks',
  },
];

export const mockFlaggedAlerts: FlaggedFeedAlert[] = [
  {
    id: 'flg-1',
    storeName: 'Apex Care Pharmacy (#STR-80225)',
    drugName: 'Atorvastatin Calcium 20mg',
    anomalyType: 'PRICE_SPIKE_80%',
    severity: 'critical',
    oldPrice: 8.50,
    newPrice: 28.90,
    timestamp: '8 mins ago',
    actionRequired: 'Automated Buy-Box Quarantine Engaged',
  },
  {
    id: 'flg-2',
    storeName: 'CostLess Apothecary (#STR-80218)',
    drugName: 'Levothyroxine Sodium 50mcg',
    anomalyType: 'STALE_FEED_>30M',
    severity: 'medium',
    oldPrice: 6.10,
    newPrice: 6.10,
    timestamp: '34 mins ago',
    actionRequired: 'EDI Polling Retry Scheduled',
  },
  {
    id: 'flg-3',
    storeName: 'QuickMeds Express (#STR-80190)',
    drugName: 'Empagliflozin 10mg',
    anomalyType: 'OUT_OF_STOCK_DRIFT',
    severity: 'high',
    oldPrice: 24.50,
    newPrice: 0,
    timestamp: '14 mins ago',
    actionRequired: 'Rerouted 4 Pending Orders',
  },
];

export const mockHourlyVelocity = [
  { hour: '08:00', orders: 420, projected: 390 },
  { hour: '09:00', orders: 740, projected: 680 },
  { hour: '10:00', orders: 1150, projected: 1020 },
  { hour: '11:00', orders: 1480, projected: 1390 },
  { hour: '12:00', orders: 1820, projected: 1750 },
  { hour: '13:00', orders: 2100, projected: 1980 },
  { hour: '14:00', orders: 2450, projected: 2280 },
  { hour: '15:00', orders: 2210, projected: 2150 },
  { hour: '16:00', orders: 1940, projected: 1890 },
  { hour: '17:00', orders: 1650, projected: 1600 },
];
